version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: test_mysql
    volumes:
      - ./db_tests/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  tests:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_NAME: test_db
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs
      - ./allure-results:/app/allure-results
    command: >
      sh -c "
      pytest ui_tests_selenium &&
      pytest ui_tests_playwright &&
      pytest api_tests &&
      pytest db_tests
      "