[pytest]
markers =
    smoke: smoke tests
    regression: regression tests
    new: new tests
    login_guest: guest login tests
    login_user: authorized user tests
    guest_user: guest user tests
    negative: negative tests
    api: API tests
    users: users API tests