[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    new: marker for new tests
    login_guest: marker for tests with guests
    login_user: marker for tests with users
    guest_user: marker for guests

